# HTTP Echo Service - CPU-bound Latency-Sensitive Workload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: benchmark
  labels:
    app: http-echo
    role: latency-sensitive
spec:
  replicas: 4
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
        role: latency-sensitive
      annotations:
        kubeattention.io/criticality: "high"
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=KubeAttention Benchmark Response"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: benchmark
spec:
  selector:
    app: http-echo
  ports:
    - port: 80
      targetPort: 8080
